In [70]:
if True: # indentiation is always 4 spaces
    print('Data Science')

Data Science


In [71]:
if False:
    print('Data Science')
print('bye for now')   

bye for now


In [72]:
if True: 
    print('Data Science')
print('bye for now')    

Data Science
bye for now


In [73]:
# to print only even number

x = 14
r = x % 2

if r == 0:
    print('Even number')
if r == 1:
    print('Odd number')

Even number


In [74]:
x = 14
r = x % 2
if r == 0:
    print('Even number')
else:
    print('Odd number')

Even number


In [75]:
x = 11
r = x % 2
if r == 0:
    print('Even number')

In [76]:
x = 5
r = x % 2
if r == 0:
    print('Even number')
print('Odd number')    

Odd number


In [77]:
x = 77
r = x % 2
if r == 0:
    print('Even number')
print('odd number')  

odd number


In [78]:
x = 100
r = x % 2
if r == 0:
    print('Even number')
else:
    print('Odd number')

Even number


In [79]:
x = 8
r = x % 2
if r == 0:
    print('Even number')
print('odd number')    

Even number
odd number


In [80]:
x = 8
r = x % 2
if r == 0:
    print('Even number')
if r == 1:
    print('Odd number')

Even number


In [81]:
x = 7
r = x % 2
if r ==0:
    print('Even number')
if r ==1:
    print('odd number')

odd number


In [82]:
x = 13
r = x % 2
if r == 0:
    print('Even number')
if r != 0:
    print('odd number')

odd number


In [83]:
x = 2
r = x % 2
if r == 0:
    print('Even number')
else:
    print('odd number')

Even number


In [84]:
x = 3
r = x % 2
if r == 0:
    print('Even number')
    if x>5:
        print('greater number')
else:
    print('odd number')

odd number


In [85]:
x = 4
r = x % 2
if r == 0:
    print('Even number')
    if x>5:
        print('greater number')
else:
    print('odd number')

Even number


In [86]:
x = 6
r = x % 2
if r == 0:
    print('Even number')
    if x>5:
        print('greter number')
    else:
        print('not greater')
else:
    print('odd number')

Even number
greter number


In [87]:
x = 2
r = x % 2
if r == 0:
    print('Even number')
    if x>5:
        print('greter number')
    else:
        print('not greater')
else:
    print('odd number')

Even number
not greater


We do have concept of (IF-ELIF-ELSE)e.g i want to print

In [88]:
x = 3
if(x==1):
    print('one')
if(x==2):
    print('two')
if(x==3):
    print('three')
if(x==4):
    print('four')

three


In [89]:
x = 4
if(x==1):
    print('one')
elif(x==2):
    print('two')
elif(x==3):
    print('three')
elif(x==4):
    print('four')

four


In [90]:
x = 5
if(x==1):
    print('one')
elif(x==2):
    print('two')
elif(x==3):
    print('three')
elif(x==4):
    print('four')
else:
    print('wrong output')

wrong output


In [91]:
x = 15
if(x==1):
    print('one')
elif(x==2):
    print('two')
elif(x==3):
    print('three')
elif(x==4):
    print('four')
else:
    print('wrong output')

wrong output


In [92]:
print('Data science')

Data science


In [93]:
print('Data science')
print('Data science')

Data science
Data science


LOOPS -- in programing world some time we keep on repeating , may be you want to repeat 5 statement so one way is copy & paste multiple times or other way is. if you want to print the datascience 10 times then what you will you cant copy for 10 times , if you want to print 1000 times then you cant do manualy . 
that is the reason why we need to apply loop ->
2 type of loops --  While loop & For loop

In [94]:
i = 1          # initializing
while i<=5:    # condition
    print('data science')
    i = i + 1  # increment

data science
data science
data science
data science
data science


In [95]:
i = 5          # initializing
while i>=1:    # condition
    print('data science')
    i = i - 1  # decrement

data science
data science
data science
data science
data science


In [96]:
i = 1          # initializing
while i<=5:    # condition
    print('data science',':',i)
    i = i + 1  # increment

data science : 1
data science : 2
data science : 3
data science : 4
data science : 5


In [97]:
i = 5          # initializing
while i>=1:    # condition
    print('data science',':',i)
    i = i - 1  # decrement

data science : 5
data science : 4
data science : 3
data science : 2
data science : 1


can we use multiple while loop || nested while loop 
to understand nested whild indepth understand you can use pycharm debug with f8 option

In [98]:
i = 1

while i<=5:
    print(' data science') # when we mention end then new line will not create
    j = 1
    while j<=4:
        print(' technology')
        j = j + 1
        
    i = i + 1
    print()

 data science
 technology
 technology
 technology
 technology

 data science
 technology
 technology
 technology
 technology

 data science
 technology
 technology
 technology
 technology

 data science
 technology
 technology
 technology
 technology

 data science
 technology
 technology
 technology
 technology



In [99]:
i = 1
while i<=5:
    print(' data science', end = "") # when we mention end then new line will not create
    j = 1
    while j<=4:
        print(' technology', end="")
        j = j + 1
        
    i = i + 1
    print()

 data science technology technology technology technology
 data science technology technology technology technology
 data science technology technology technology technology
 data science technology technology technology technology
 data science technology technology technology technology


In [100]:
i = 1
while i<=5:
    print(' data science', end = "  *") # when we mention end then new line will not create
    j = 1
    while j<=4:
        print(' technology', end="  *")
        j = j + 1
        
    i = i + 1
    print()

 data science  * technology  * technology  * technology  * technology  *
 data science  * technology  * technology  * technology  * technology  *
 data science  * technology  * technology  * technology  * technology  *
 data science  * technology  * technology  * technology  * technology  *
 data science  * technology  * technology  * technology  * technology  *


In [101]:
i = 1
while i <= 4 :
    j = 0
    while  j <= 3 :
        print(i*j, end=" ")
        j += 1
    print()
    i += 1

0 1 2 3 
0 2 4 6 
0 3 6 9 
0 4 8 12 


FOR LOOP  -
normally while loop it work with condition but for loop it will work with sequence (list, string,int)


In [102]:
name = 'nit'
for i in name:
    print(i)

n
i
t


In [103]:
name1 = [1,3.5,'hallo']

for i in name1:
    print(i)

1
3.5
hallo


In [104]:
for i in [2, 3, 7.8, 'hi']:
    print(i)

2
3
7.8
hi


In [105]:
for i in range(5):
    print(i)

0
1
2
3
4


In [106]:
for i in range(1,5):
    print(i)

1
2
3
4


In [107]:
for i in range(1,10,3):
    print(i)

1
4
7


In [108]:
# print the numer which is not divisible by 5

for i in range(1,11):
    
    if i%5 != 0 :
      print(i)

1
2
3
4
6
7
8
9


In [109]:
# can you write the python code for 5 multiplication table 

for i in range(1,51):
    
    if i%5 == 0:
      print(i)

5
10
15
20
25
30
35
40
45
50


LETS DISCUSS ABOUT 3 KEYWORDS -- BREAK || CONTINUE || PASS
BREAK STATEMNT - if you apply break statment in a loop then it will end the loop
 Pass = skips block of code( function, class etc)
 Continue= skips 1 step/iteration during loop 
 Break= jumps out of the function/loop

In [110]:
for i in range(1,11):
    print(i)

1
2
3
4
5
6
7
8
9
10


In [111]:
for i in range(1,11):
    if i == 5:
        break #==> While you work with computer vision project

In [112]:
for i in range(1,11):
    if i == 5:
        break
    print(i)

1
2
3
4


In [113]:
for i in range(1,11):
    if i == 5:
        break
print(i)

5


In [114]:
for i in range(1,11):
    if i == 5:
        continue
    print(i)

1
2
3
4
6
7
8
9
10


In [115]:
for i in range(1,11):
    if i == 5:
        continue
    print('hello',i)

hello 1
hello 2
hello 3
hello 4
hello 6
hello 7
hello 8
hello 9
hello 10


In [116]:
for i in range(1,11):
    pass

In [117]:
print('# # # #')
print('# # # #')
print('# # # #')
print('# # # #')

# # # #
# # # #
# # # #
# # # #


In [118]:
for j in range(4):
    print('#', end=" ")

# # # # 

In [119]:
for j in range(4):
    print('#', end=" ")
    
for j in range(4):
    print('#', end=" ")

# # # # # # # # 

In [120]:
for j in range(4):
    print('#', end=" ")

print()

for j in range(4):
    print('#', end=" ")

# # # # 
# # # # 

In [121]:
for j in range(4):
    print('#', end=" ")

print()

for j in range(4):
    print('#', end=" ")
    
print()

for j in range(4):
    print('#', end=" ")
    
print()
 
for j in range(4):
    print('#', end=" ")

# # # # 
# # # # 
# # # # 
# # # # 

In [122]:
for i in range(4):
    for j in range(4):
        print('#', end=" ")
    print()

# # # # 
# # # # 
# # # # 
# # # # 


In [123]:
for i in range(5):
    for j in range(i):
        print('#', end=" ")
    print()


# 
# # 
# # # 
# # # # 


In [124]:
for i in range(5):
    for j in range(i+1):
        print('#', end=" ")
    print()

# 
# # 
# # # 
# # # # 
# # # # # 


In [125]:
for i in range(5):
    for j in range(4-i):
        print('#', end=" ")
    print()

# # # # 
# # # 
# # 
# 



In [126]:
for i in range(5):
    for j in range(4-i):
        print('*', end=" ")
    print()

* * * * 
* * * 
* * 
* 



FOR | ELSE IN PYTHON

In other language for else not supportable but in python it is supportable eg-lets print the number from 1-20 &we dont want print number which is divisible by 5

In [127]:
nums = [12,15,18,21,26]

for num in nums:
    if num % 5 == 0:
        print(num)

15


In [128]:
nums = [12,14,18,21,25]
for num in nums:
    if num % 5 == 0:
        print(num)

25


In [129]:
nums = [12,14,18,21,25,20]
for num in nums:
    if num % 5 == 0:
        print(num)

25
20


In [130]:
nums = [12,14,18,21,25,20]
for num in nums:
    if num % 5 == 0:
        print(num)
        break

25


In [131]:
nums = [10,14,18,21,20,25]
for num in nums:
    if num % 5 == 0:
        print(num)
        break

10


In [132]:
nums = [7,14,18,21,23,27]
for num in nums:
    if num % 5 == 0:
        print(num)

In [133]:
nums = [7,14,18,21,23,27,22]
for num in nums:
    if num % 5 == 0:
        print(num)
        break
    else:
        print('Number not found')

Number not found
Number not found
Number not found
Number not found
Number not found
Number not found
Number not found


In [134]:
nums = [7,14,18,21,20,27]
for num in nums:
    if num % 5 == 0:
        print(num)
else:
    print('Not found')

20
Not found


In [135]:
nums = [7,14,18,21,20,27]
for num in nums:
    if num % 5 == 0:
        print(num)
        break
else:
    print('not found')

20


In [136]:
num = 12

for i in range(2,num):
    if num % i == 0:
        print('Not prime number')
        break
else:
    print('prime number')

Not prime number


In [137]:
num = 13
for i in range(2,num):
    if num % i == 0:
        print('Not prime number')
        break
else:
    print('prime number')

prime number


In [138]:
from array import 
arr = array('i',[])
n = int(input('Enter the length of the array'))

for i in range(5):
    x = int(input('Enter the next value'))
    arr.append(x)
    print(arr)

SyntaxError: invalid syntax (1908451726.py, line 1)

In [139]:
from numpy import *
arr = array([1,2,3,4,5])
print(arr)
type(arr)

[1 2 3 4 5]


numpy.ndarray

In [140]:
print(arr.dtype)

int32


In [141]:
arr = array([1,2,3,4,5.9])
print(arr)

[1.  2.  3.  4.  5.9]


In [142]:
print(arr.dtype)

float64


In [143]:
arr2 = array([1,2,3,4,5.9],float)
arr2

array([1. , 2. , 3. , 4. , 5.9])

In [144]:
arr3 = array([1,2,3,4,5.6],int)
arr3

array([1, 2, 3, 4, 5])

In [145]:
import numpy as np

In [146]:
arr4 = np.linspace(0, 16, 10)
arr4

array([ 0.        ,  1.77777778,  3.55555556,  5.33333333,  7.11111111,
        8.88888889, 10.66666667, 12.44444444, 14.22222222, 16.        ])

In [147]:
arr5 = np.arange(0,10,2)
arr5

array([0, 2, 4, 6, 8])

In [148]:
arr6 = np.zeros(5)
arr6

array([0., 0., 0., 0., 0.])

In [149]:
arr7 = np.ones(5)
arr7

array([1., 1., 1., 1., 1.])